version: '3.8'

services:
  redis:
    image: redis:7.2.5-alpine    

  django:
    container_name: django
    build: 
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # windows config
      - type: bind
        source: ./dcelery
        target: /usr/scr/app/
      # unix config
      # - ./dcelery:/usr/scr/app/
    working_dir: /usr/scr/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj010j0f
      - ALLOWED_HOSTS=localhost,127.0.0.1

  celery:
    container_name: celery
    build: 
      context: ./dcelery
    command: celery --app=dcelery worker -l INFO
    volumes:
      # windows config
      - type: bind
        source: ./dcelery
        target: /usr/scr/app/
      # unix config
      # - ./dcelery:/usr/scr/app/
    working_dir: /usr/scr/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj010j0f
      - ALLOWED_HOSTS=localhost,127.0.0.1